# Generated by Django 5.1.6 on 2025-03-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_text",
            field=models.CharField(max_length=260, unique=True),
        ),
    ]
